# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|

  config.ssh.insert_key = true
  config.ssh.forward_agent = true

  config.vm.define "worker1" do |worker|

    worker.vm.box = "ubuntu/xenial64"
    
    worker.vm.hostname = "worker1"
    
    worker.vm.network "private_network", ip: "192.168.33.11"
    
    worker.vm.provider "virtualbox" do |v|
        v.name = "worker1"
        v.memory = 1024
        v.gui = false
    end

    worker.vm.provision "shell",
      inline: "apt-get update && apt-get install -y apt-transport-https"
    
    worker.vm.provision "shell",
      inline: "curl -s https://packages.cloud.google.com/apt/doc/apt-key.gpg | apt-key add -"

    worker.vm.provision "shell",
      inline: "cat <<EOF > /etc/apt/sources.list.d/kubernetes.list
deb http://apt.kubernetes.io/ kubernetes-xenial main
EOF"
  
    worker.vm.provision "shell",
      inline: "apt-get update"

    worker.vm.provision "shell",
      inline: "apt-get install -y kubelet kubeadm kubectl kubernetes-cni docker.io"
  
    worker.vm.provision "shell",
      inline: "kubeadm join --token=f4f327.2195e4e194e45b0b 192.168.33.10:6443"

  end  
end
